### ISSUE TITLE
Add vizyBlock names as data-name or class to the vizyBlocks

### ISSUE THREAD

**Issue by davidhellmann** [verbb/vizy#96]
We do from time to time something with control panel css to overwrite style within the control panel
Would be nice to have here:
![image](https://user-images.githubusercontent.com/764292/150701290-a6ac0388-5b91-4699-83e0-a1673f62493a.png)

the block names to select it via css. 

For stuff like that
```css
.vui-rich-text .vizyblock {
  margin: 20px 0;
}

.vui-rich-text .vizyblock ~*:not(.vizyblock[data-name="blockSection"]) {
  width: calc(100% - 32px);
  margin-left: 32px;
}

.vui-rich-text .vizyblock:first-of-type {
  margin-top: 10px;
}

.vui-rich-text .vizyblock:last-of-type {
  margin-bottom: 10px;
}
```
![image](https://user-images.githubusercontent.com/764292/150701717-4d9d6335-7e60-471d-a075-adbde7744c58.png)

We use this in matrix fields too. So the user can open a section to put content together. If he creates another section the old section is self closing. So it's possible to put content in another block without doing it :)
